// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExecuteRename(arg1:Array<main.FileItem>,arg2:Array<main.RenameRule>):Promise<Array<main.FileItem>>;

export function ListSubDirs(arg1:string):Promise<Array<main.FileItem>>;

export function ListSubFiles(arg1:string):Promise<Array<main.FileItem>>;

export function LoadScripts():Promise<Array<main.ScriptItem>>;

export function PreviewNames(arg1:Array<main.FileItem>,arg2:Array<main.RenameRule>):Promise<Array<main.FileItem>>;

export function SaveScripts(arg1:Array<main.ScriptItem>):Promise<boolean>;

export function SelectFiles():Promise<Array<main.FileItem>>;

export function SelectTargetDirectory():Promise<string>;

export function SelectWorkingDirectory():Promise<string>;
