// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteRename(arg1, arg2) {
  return window['go']['main']['App']['ExecuteRename'](arg1, arg2);
}

export function ListSubDirs(arg1) {
  return window['go']['main']['App']['ListSubDirs'](arg1);
}

export function ListSubFiles(arg1) {
  return window['go']['main']['App']['ListSubFiles'](arg1);
}

export function LoadScripts() {
  return window['go']['main']['App']['LoadScripts']();
}

export function PreviewNames(arg1, arg2) {
  return window['go']['main']['App']['PreviewNames'](arg1, arg2);
}

export function SaveScripts(arg1) {
  return window['go']['main']['App']['SaveScripts'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectTargetDirectory() {
  return window['go']['main']['App']['SelectTargetDirectory']();
}

export function SelectWorkingDirectory() {
  return window['go']['main']['App']['SelectWorkingDirectory']();
}
